DROP TABLE IF EXISTS EMPLOYEE_DETAIL;
  
CREATE TABLE EMPLOYEE_DETAIL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME_name VARCHAR(250) NOT NULL,
  GENDER VARCHAR(250) DEFAULT NULL,
  DOB DATE DEFAULT NULL,
  DEPARTMENT VARCHAR(250) DEFAULT NULL,
);